/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_RAMPC_v2_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[136] = {132, 1, 0, 132, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131};
static const casadi_int casadi_s4[31] = {27, 1, 0, 27, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26};

/* quadrotor_RAMPC_v2_constr_h_fun:(i0[7],i1[10],i2[],i3[132])->(o0[27]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=5.4184786818321906e-01;
  a2=arg[0]? arg[0][6] : 0;
  a3=(a1*a2);
  a3=(a0+a3);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[0]? arg[0][1] : 0;
  a4=2.2732385197231011e-01;
  a5=(a4*a2);
  a5=(a3+a5);
  if (res[0]!=0) res[0][1]=a5;
  a1=(a1*a2);
  a1=(a1-a0);
  if (res[0]!=0) res[0][2]=a1;
  a4=(a4*a2);
  a4=(a4-a3);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0]? arg[0][2] : 0;
  a1=2.0481784543190165e-01;
  a5=(a1*a2);
  a5=(a4+a5);
  if (res[0]!=0) res[0][4]=a5;
  a5=arg[0]? arg[0][3] : 0;
  a6=8.0988154313854899e-01;
  a7=(a6*a2);
  a7=(a5+a7);
  if (res[0]!=0) res[0][5]=a7;
  a7=arg[0]? arg[0][4] : 0;
  a8=3.9463455784000195e-01;
  a9=(a8*a2);
  a9=(a7+a9);
  if (res[0]!=0) res[0][6]=a9;
  a9=arg[0]? arg[0][5] : 0;
  a10=1.5742998630435918e+00;
  a11=(a10*a2);
  a11=(a9+a11);
  if (res[0]!=0) res[0][7]=a11;
  a1=(a1*a2);
  a1=(a1-a4);
  if (res[0]!=0) res[0][8]=a1;
  a6=(a6*a2);
  a6=(a6-a5);
  if (res[0]!=0) res[0][9]=a6;
  a8=(a8*a2);
  a8=(a8-a7);
  if (res[0]!=0) res[0][10]=a8;
  a10=(a10*a2);
  a10=(a10-a9);
  if (res[0]!=0) res[0][11]=a10;
  a10=arg[1]? arg[1][0] : 0;
  a9=7.6694561124289573e-01;
  a8=(a9*a2);
  a8=(a10+a8);
  if (res[0]!=0) res[0][12]=a8;
  a8=arg[1]? arg[1][1] : 0;
  a7=7.6693189676533913e-01;
  a6=(a7*a2);
  a6=(a8+a6);
  if (res[0]!=0) res[0][13]=a6;
  a9=(a9*a2);
  a9=(a9-a10);
  if (res[0]!=0) res[0][14]=a9;
  a7=(a7*a2);
  a7=(a7-a8);
  if (res[0]!=0) res[0][15]=a7;
  a7=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][16]=a7;
  a7=arg[1]? arg[1][3] : 0;
  if (res[0]!=0) res[0][17]=a7;
  a7=arg[1]? arg[1][4] : 0;
  if (res[0]!=0) res[0][18]=a7;
  a7=arg[1]? arg[1][5] : 0;
  if (res[0]!=0) res[0][19]=a7;
  a7=arg[1]? arg[1][6] : 0;
  if (res[0]!=0) res[0][20]=a7;
  a7=arg[1]? arg[1][7] : 0;
  if (res[0]!=0) res[0][21]=a7;
  a7=arg[1]? arg[1][8] : 0;
  if (res[0]!=0) res[0][22]=a7;
  a7=arg[1]? arg[1][9] : 0;
  if (res[0]!=0) res[0][23]=a7;
  a7=1.6000000000000000e-01;
  a8=1.;
  a8=(a0-a8);
  a8=casadi_sq(a8);
  a9=1.2500000000000000e+00;
  a10=(a3-a9);
  a10=casadi_sq(a10);
  a8=(a8+a10);
  a8=sqrt(a8);
  a8=(a7-a8);
  a10=5.4242866255517297e-01;
  a10=(a10*a2);
  a8=(a8+a10);
  if (res[0]!=0) res[0][24]=a8;
  a8=1.5000000000000000e+00;
  a8=(a0-a8);
  a8=casadi_sq(a8);
  a9=(a3-a9);
  a9=casadi_sq(a9);
  a8=(a8+a9);
  a8=sqrt(a8);
  a8=(a7-a8);
  a9=5.4243336345060678e-01;
  a9=(a9*a2);
  a8=(a8+a9);
  if (res[0]!=0) res[0][25]=a8;
  a8=1.2000000000000000e+00;
  a0=(a0-a8);
  a0=casadi_sq(a0);
  a8=1.7500000000000000e+00;
  a3=(a3-a8);
  a3=casadi_sq(a3);
  a0=(a0+a3);
  a0=sqrt(a0);
  a7=(a7-a0);
  a0=5.4222437246644040e-01;
  a0=(a0*a2);
  a7=(a7+a0);
  if (res[0]!=0) res[0][26]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_RAMPC_v2_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_RAMPC_v2_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_RAMPC_v2_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_RAMPC_v2_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_RAMPC_v2_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_RAMPC_v2_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_RAMPC_v2_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_RAMPC_v2_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_RAMPC_v2_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_RAMPC_v2_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_RAMPC_v2_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_RAMPC_v2_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_RAMPC_v2_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_RAMPC_v2_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_RAMPC_v2_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_RAMPC_v2_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
