/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[80] = {76, 1, 0, 76, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const casadi_int casadi_s3[73] = {9, 7, 0, 9, 18, 27, 36, 45, 54, 63, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s4[12] = {9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess:(i0[7],i1[2],i2[7],i3[76])->(o0[7],o1[9x7],o2[9x9,0nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a7, a8, a9;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=arg[3]? arg[3][7] : 0;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=arg[3]? arg[3][14] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a7=(a5*a6);
  a2=(a2+a7);
  a7=arg[3]? arg[3][21] : 0;
  a8=arg[0]? arg[0][3] : 0;
  a9=(a7*a8);
  a2=(a2+a9);
  a9=arg[3]? arg[3][28] : 0;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a9*a10);
  a2=(a2+a11);
  a11=arg[3]? arg[3][35] : 0;
  a12=arg[0]? arg[0][5] : 0;
  a13=(a11*a12);
  a2=(a2+a13);
  a13=arg[3]? arg[3][42] : 0;
  a14=arg[0]? arg[0][6] : 0;
  a15=(a13*a14);
  a2=(a2+a15);
  a15=arg[3]? arg[3][49] : 0;
  a16=arg[1]? arg[1][0] : 0;
  a17=(a15*a16);
  a18=arg[3]? arg[3][56] : 0;
  a19=arg[1]? arg[1][1] : 0;
  a20=(a18*a19);
  a17=(a17+a20);
  a2=(a2+a17);
  a17=arg[3]? arg[3][63] : 0;
  a2=(a2+a17);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[3]? arg[3][1] : 0;
  a17=(a2*a1);
  a20=arg[3]? arg[3][8] : 0;
  a21=(a20*a4);
  a17=(a17+a21);
  a21=arg[3]? arg[3][15] : 0;
  a22=(a21*a6);
  a17=(a17+a22);
  a22=arg[3]? arg[3][22] : 0;
  a23=(a22*a8);
  a17=(a17+a23);
  a23=arg[3]? arg[3][29] : 0;
  a24=(a23*a10);
  a17=(a17+a24);
  a24=arg[3]? arg[3][36] : 0;
  a25=(a24*a12);
  a17=(a17+a25);
  a25=arg[3]? arg[3][43] : 0;
  a26=(a25*a14);
  a17=(a17+a26);
  a26=arg[3]? arg[3][50] : 0;
  a27=(a26*a16);
  a28=arg[3]? arg[3][57] : 0;
  a29=(a28*a19);
  a27=(a27+a29);
  a17=(a17+a27);
  a27=arg[3]? arg[3][64] : 0;
  a17=(a17+a27);
  if (res[0]!=0) res[0][1]=a17;
  a17=arg[3]? arg[3][2] : 0;
  a27=(a17*a1);
  a29=arg[3]? arg[3][9] : 0;
  a30=(a29*a4);
  a27=(a27+a30);
  a30=arg[3]? arg[3][16] : 0;
  a31=(a30*a6);
  a27=(a27+a31);
  a31=arg[3]? arg[3][23] : 0;
  a32=(a31*a8);
  a27=(a27+a32);
  a32=arg[3]? arg[3][30] : 0;
  a33=(a32*a10);
  a27=(a27+a33);
  a33=arg[3]? arg[3][37] : 0;
  a34=(a33*a12);
  a27=(a27+a34);
  a34=arg[3]? arg[3][44] : 0;
  a35=(a34*a14);
  a27=(a27+a35);
  a35=arg[3]? arg[3][51] : 0;
  a36=(a35*a16);
  a37=arg[3]? arg[3][58] : 0;
  a38=(a37*a19);
  a36=(a36+a38);
  a27=(a27+a36);
  a36=arg[3]? arg[3][65] : 0;
  a27=(a27+a36);
  if (res[0]!=0) res[0][2]=a27;
  a27=arg[3]? arg[3][3] : 0;
  a36=(a27*a1);
  a38=arg[3]? arg[3][10] : 0;
  a39=(a38*a4);
  a36=(a36+a39);
  a39=arg[3]? arg[3][17] : 0;
  a40=(a39*a6);
  a36=(a36+a40);
  a40=arg[3]? arg[3][24] : 0;
  a41=(a40*a8);
  a36=(a36+a41);
  a41=arg[3]? arg[3][31] : 0;
  a42=(a41*a10);
  a36=(a36+a42);
  a42=arg[3]? arg[3][38] : 0;
  a43=(a42*a12);
  a36=(a36+a43);
  a43=arg[3]? arg[3][45] : 0;
  a44=(a43*a14);
  a36=(a36+a44);
  a44=arg[3]? arg[3][52] : 0;
  a45=(a44*a16);
  a46=arg[3]? arg[3][59] : 0;
  a47=(a46*a19);
  a45=(a45+a47);
  a36=(a36+a45);
  a45=arg[3]? arg[3][66] : 0;
  a36=(a36+a45);
  if (res[0]!=0) res[0][3]=a36;
  a36=arg[3]? arg[3][4] : 0;
  a45=(a36*a1);
  a47=arg[3]? arg[3][11] : 0;
  a48=(a47*a4);
  a45=(a45+a48);
  a48=arg[3]? arg[3][18] : 0;
  a49=(a48*a6);
  a45=(a45+a49);
  a49=arg[3]? arg[3][25] : 0;
  a50=(a49*a8);
  a45=(a45+a50);
  a50=arg[3]? arg[3][32] : 0;
  a51=(a50*a10);
  a45=(a45+a51);
  a51=arg[3]? arg[3][39] : 0;
  a52=(a51*a12);
  a45=(a45+a52);
  a52=arg[3]? arg[3][46] : 0;
  a53=(a52*a14);
  a45=(a45+a53);
  a53=arg[3]? arg[3][53] : 0;
  a54=(a53*a16);
  a55=arg[3]? arg[3][60] : 0;
  a56=(a55*a19);
  a54=(a54+a56);
  a45=(a45+a54);
  a54=arg[3]? arg[3][67] : 0;
  a45=(a45+a54);
  if (res[0]!=0) res[0][4]=a45;
  a45=arg[3]? arg[3][5] : 0;
  a54=(a45*a1);
  a56=arg[3]? arg[3][12] : 0;
  a57=(a56*a4);
  a54=(a54+a57);
  a57=arg[3]? arg[3][19] : 0;
  a58=(a57*a6);
  a54=(a54+a58);
  a58=arg[3]? arg[3][26] : 0;
  a59=(a58*a8);
  a54=(a54+a59);
  a59=arg[3]? arg[3][33] : 0;
  a60=(a59*a10);
  a54=(a54+a60);
  a60=arg[3]? arg[3][40] : 0;
  a61=(a60*a12);
  a54=(a54+a61);
  a61=arg[3]? arg[3][47] : 0;
  a62=(a61*a14);
  a54=(a54+a62);
  a62=arg[3]? arg[3][54] : 0;
  a63=(a62*a16);
  a64=arg[3]? arg[3][61] : 0;
  a65=(a64*a19);
  a63=(a63+a65);
  a54=(a54+a63);
  a63=arg[3]? arg[3][68] : 0;
  a54=(a54+a63);
  if (res[0]!=0) res[0][5]=a54;
  a54=arg[3]? arg[3][6] : 0;
  a1=(a54*a1);
  a63=arg[3]? arg[3][13] : 0;
  a4=(a63*a4);
  a1=(a1+a4);
  a4=arg[3]? arg[3][20] : 0;
  a6=(a4*a6);
  a1=(a1+a6);
  a6=arg[3]? arg[3][27] : 0;
  a8=(a6*a8);
  a1=(a1+a8);
  a8=arg[3]? arg[3][34] : 0;
  a10=(a8*a10);
  a1=(a1+a10);
  a10=arg[3]? arg[3][41] : 0;
  a12=(a10*a12);
  a1=(a1+a12);
  a12=arg[3]? arg[3][48] : 0;
  a14=(a12*a14);
  a1=(a1+a14);
  a14=arg[3]? arg[3][55] : 0;
  a16=(a14*a16);
  a65=arg[3]? arg[3][62] : 0;
  a19=(a65*a19);
  a16=(a16+a19);
  a1=(a1+a16);
  a16=arg[3]? arg[3][69] : 0;
  a1=(a1+a16);
  if (res[0]!=0) res[0][6]=a1;
  if (res[1]!=0) res[1][0]=a15;
  if (res[1]!=0) res[1][1]=a18;
  if (res[1]!=0) res[1][2]=a0;
  if (res[1]!=0) res[1][3]=a3;
  if (res[1]!=0) res[1][4]=a5;
  if (res[1]!=0) res[1][5]=a7;
  if (res[1]!=0) res[1][6]=a9;
  if (res[1]!=0) res[1][7]=a11;
  if (res[1]!=0) res[1][8]=a13;
  if (res[1]!=0) res[1][9]=a26;
  if (res[1]!=0) res[1][10]=a28;
  if (res[1]!=0) res[1][11]=a2;
  if (res[1]!=0) res[1][12]=a20;
  if (res[1]!=0) res[1][13]=a21;
  if (res[1]!=0) res[1][14]=a22;
  if (res[1]!=0) res[1][15]=a23;
  if (res[1]!=0) res[1][16]=a24;
  if (res[1]!=0) res[1][17]=a25;
  if (res[1]!=0) res[1][18]=a35;
  if (res[1]!=0) res[1][19]=a37;
  if (res[1]!=0) res[1][20]=a17;
  if (res[1]!=0) res[1][21]=a29;
  if (res[1]!=0) res[1][22]=a30;
  if (res[1]!=0) res[1][23]=a31;
  if (res[1]!=0) res[1][24]=a32;
  if (res[1]!=0) res[1][25]=a33;
  if (res[1]!=0) res[1][26]=a34;
  if (res[1]!=0) res[1][27]=a44;
  if (res[1]!=0) res[1][28]=a46;
  if (res[1]!=0) res[1][29]=a27;
  if (res[1]!=0) res[1][30]=a38;
  if (res[1]!=0) res[1][31]=a39;
  if (res[1]!=0) res[1][32]=a40;
  if (res[1]!=0) res[1][33]=a41;
  if (res[1]!=0) res[1][34]=a42;
  if (res[1]!=0) res[1][35]=a43;
  if (res[1]!=0) res[1][36]=a53;
  if (res[1]!=0) res[1][37]=a55;
  if (res[1]!=0) res[1][38]=a36;
  if (res[1]!=0) res[1][39]=a47;
  if (res[1]!=0) res[1][40]=a48;
  if (res[1]!=0) res[1][41]=a49;
  if (res[1]!=0) res[1][42]=a50;
  if (res[1]!=0) res[1][43]=a51;
  if (res[1]!=0) res[1][44]=a52;
  if (res[1]!=0) res[1][45]=a62;
  if (res[1]!=0) res[1][46]=a64;
  if (res[1]!=0) res[1][47]=a45;
  if (res[1]!=0) res[1][48]=a56;
  if (res[1]!=0) res[1][49]=a57;
  if (res[1]!=0) res[1][50]=a58;
  if (res[1]!=0) res[1][51]=a59;
  if (res[1]!=0) res[1][52]=a60;
  if (res[1]!=0) res[1][53]=a61;
  if (res[1]!=0) res[1][54]=a14;
  if (res[1]!=0) res[1][55]=a65;
  if (res[1]!=0) res[1][56]=a54;
  if (res[1]!=0) res[1][57]=a63;
  if (res[1]!=0) res[1][58]=a4;
  if (res[1]!=0) res[1][59]=a6;
  if (res[1]!=0) res[1][60]=a8;
  if (res[1]!=0) res[1][61]=a10;
  if (res[1]!=0) res[1][62]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_with_gp_cl_v1_dyn_disc_phi_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
