/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s4[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s5[31] = {4, 10, 0, 3, 4, 5, 6, 8, 10, 12, 14, 16, 18, 1, 2, 3, 3, 1, 2, 1, 3, 2, 3, 1, 3, 2, 3, 0, 3, 0, 3};
static const casadi_int casadi_s6[3] = {10, 0, 0};

/* msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt:(i0[3],i1,i2[],i3[17])->(o0[10],o1[4x10,18nz],o2[10x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][2] : 0;
  a1=casadi_sq(a0);
  a2=8.7296923148481554e+01;
  a3=arg[3]? arg[3][15] : 0;
  a4=arg[0]? arg[0][0] : 0;
  a5=(a3-a4);
  a2=(a2*a5);
  a6=2.9566131266531215e+01;
  a7=arg[3]? arg[3][16] : 0;
  a8=arg[0]? arg[0][1] : 0;
  a9=(a7-a8);
  a10=(a6*a9);
  a2=(a2+a10);
  a10=(a3-a4);
  a11=(a2*a10);
  a6=(a6*a5);
  a5=3.1121273612128476e+01;
  a5=(a5*a9);
  a6=(a6+a5);
  a5=(a7-a8);
  a9=(a6*a5);
  a11=(a11+a9);
  a1=(a1-a11);
  if (res[0]!=0) res[0][0]=a1;
  if (res[0]!=0) res[0][1]=a0;
  a3=(a4-a3);
  if (res[0]!=0) res[0][2]=a3;
  a7=(a8-a7);
  if (res[0]!=0) res[0][3]=a7;
  a7=1.2995978553774173e-01;
  a3=(a7*a0);
  a3=(a4+a3);
  if (res[0]!=0) res[0][4]=a3;
  a3=2.1766057570755215e-01;
  a1=(a3*a0);
  a1=(a8+a1);
  if (res[0]!=0) res[0][5]=a1;
  a1=(a7*a0);
  a1=(a1-a4);
  if (res[0]!=0) res[0][6]=a1;
  a1=(a3*a0);
  a1=(a1-a8);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[1]? arg[1][0] : 0;
  a8=3.4059514581103578e-01;
  a4=(a8*a0);
  a4=(a1+a4);
  if (res[0]!=0) res[0][8]=a4;
  a4=(a8*a0);
  a4=(a4-a1);
  if (res[0]!=0) res[0][9]=a4;
  a4=-8.7296923148481554e+01;
  a4=(a4*a10);
  a4=(a4-a2);
  a2=-2.9566131266531215e+01;
  a1=(a2*a5);
  a4=(a4+a1);
  a4=(-a4);
  if (res[1]!=0) res[1][0]=a4;
  a2=(a2*a10);
  a10=-3.1121273612128476e+01;
  a10=(a10*a5);
  a10=(a10-a6);
  a2=(a2+a10);
  a2=(-a2);
  if (res[1]!=0) res[1][1]=a2;
  a0=(a0+a0);
  if (res[1]!=0) res[1][2]=a0;
  a0=1.;
  if (res[1]!=0) res[1][3]=a0;
  if (res[1]!=0) res[1][4]=a0;
  if (res[1]!=0) res[1][5]=a0;
  if (res[1]!=0) res[1][6]=a0;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a0;
  if (res[1]!=0) res[1][9]=a3;
  a2=-1.;
  if (res[1]!=0) res[1][10]=a2;
  if (res[1]!=0) res[1][11]=a7;
  if (res[1]!=0) res[1][12]=a2;
  if (res[1]!=0) res[1][13]=a3;
  if (res[1]!=0) res[1][14]=a0;
  if (res[1]!=0) res[1][15]=a8;
  if (res[1]!=0) res[1][16]=a2;
  if (res[1]!=0) res[1][17]=a8;
  return 0;
}

CASADI_SYMBOL_EXPORT int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int msds_with_gp_cl_v1_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
